### PR TITLE
Version 1.46 -- new property .AppID for RegisterWithThor to identify …

### PR DESCRIPTION
**Pull request by Jimrnelson**
…what Project a tool comes from

### CODE REVIEW

**Comment by lscheffler** [comment]
I do not understand what this is used for?

**Comment by Jimrnelson** [comment]
@lscheffler @tbleken @DougHennig 

Ha!  Implemented and tested this last night, ran out of gas, with intent to describe first thing this morning (4:50 here).

This new property .AppID is to be used in Thor tools to describe what CFU Project they belong to.  (I will describe the use for this at a later time.)

For projects that create Thor tools by using .RegisterWithThor, the VersionTemplate.txt file has one line added:

image

The only instance of this right now is in the tool that runs Object Explorer, where it looks like this:

image

Over time, I will be making modifications to projects that I manage to set this property and also sending notifications from those that I do not manage.

**Comment by lscheffler** [comment]
You run out of gas? Usually I stop if my beer is empty. To lazy to walk in the cellar to gather a second bottle. :)   
So it exposes this ID through .RegisterWithThor. Is this expected to be the same ID as the project uses in the file in the *Updates* directory or is this independent?

**Comment by Jimrnelson** [comment]
You may not have noticed in the first image that the value is set to {AppID}, which is the exact name used Thor updater and also in GitHub.

**Comment by lscheffler** [comment]
Oh, I noticed. Anyway, this could be laziness, so I better ask. :D

**Comment by Jimrnelson** [comment]
@DougHennig 

As part of this mini-project to be able to have tools identify what project they originate in, there is a one line fix in PEMEditor that will take care of all the tools that come from PEMEditor (quite a few, actually.)

Now, I've been avoiding PEMEditor for many years and have not yet forked a copy of it, so I am asking if maybe you can make this change in PEME_CreateThorTools.PRG.

If PEMEditor is then rebuilt and uploaded without changing the version number or date, I can test that all of these tools show up correctly without bothering everybody else.  (It's tricky business trying out changes in CFU.)

No hurries on this one, just wanted to get it in the queue.

image

**Comment by DougHennig** [comment]
Do you need the zip file in ThorUpdater updated too?

**Comment by Jimrnelson** [comment]
Just like you're doing an entire install.

If that can be done without changing the version or date, fine.

If not, just record it as a incremental change and let the world try it.

**Comment by DougHennig** [comment]
Done

**Comment by Jimrnelson** [comment]
Well, rats, that didn't change anything.

I'll have to fork PEME and see what's going on.

Thanks.

**Comment by Jimrnelson** [comment]
Well, un-rats.

I was quite wrong about being wrong.

That worked as hoped for.  (It was just that the new property did not appear where expected.)

Thanks, this is fine.

**Comment by lscheffler** [comment]
@Jimrnelson Since .RegisterWithThor has a good chance to run out of the version file, you could preload the property with the ID while creating the ThorInfo object. I mean, the calling structures knows this ID anyway.    
So the value needs only to be set if calling from outside this structure.   
Just my 0,02€cent

**Comment by Jimrnelson** [comment]
> @Jimrnelson Since .RegisterWithThor has a good chance to run out of the version file, you could preload the property with the ID while creating the ThorInfo object. I mean, the calling structures knows this ID anyway. So the value needs only to be set if calling from outside this structure. Just my 0,02€cent

@lscheffler 

Now that Doug has taken care of this for PEMEditor, that has pretty much become a moot point.   There are only a few projects that register tools with Thor, most of which are so old that we are not gonna both changing them.

The only one that remains in GF, which is not run out of the version file anyway.  There are three files registered with Thor by GF, so one line will need to be added for each of them, eventually.

**Comment by lscheffler** [comment]
Do I read I should push a new GF with this property?

**Comment by Jimrnelson** [comment]
No, it is of low enough interest that it can certainly wait until your next release.

In fact, GF is a special case that can be identified in a different way, so it might not be necessary for you to do anything at all.  

I'll get back to you; in the meantime, nothing is needed on your end.

**Comment by lscheffler** [comment]
In https://github.com/VFPX/Thor/pull/144#issuecomment-1675880022 you mention *VersionTemplate.txt*. But this is a file of [VFPXDeployment](https://github.com/VFPX/VFPXDeployment)? Will you push an updated version?

**Comment by Jimrnelson** [comment]
> In [#144 (comment)](https://github.com/VFPX/Thor/pull/144#issuecomment-1675880022) you mention _VersionTemplate.txt_. But this is a file of [VFPXDeployment](https://github.com/VFPX/VFPXDeployment)? Will you push an updated version?

@lscheffler 

This is actually a file in all projects, but, as noted, the change only applies to those few thar register a tool (or tools) with Thor, primarily PEMEditor and GF.  At the moment, I know of no other projects that require this change

VFPX Deployment does not register with Thor, so there is no need to modify this file there.

**Comment by lscheffler** [comment]
I understand that you mean the Version.txt (or the like) per project to *set* this property. Only you mentioned distinct **VersionTemplate.txt**  - and this exist only as the *template* for the version-file in VFPXDeplyment. So I'm confused.

Anyway, if you could place the code in this VFPXDeplyment template and push, you safe me to copy it from a picture. :D

**Comment by Jimrnelson** [comment]
I see file Version.txt in all the GitHub repositories that I have forked.

**Comment by lscheffler** [comment]
I think GF or FoxBin2Prg are special. That's not the problem, this I understand.

**Comment by Jimrnelson** [comment]
I don't know what you think the problem is.

The only places where I believe .AppID were needed have been addressed.

**Comment by lscheffler** [comment]
Not really a problem, only you use the term Version**Template**.txt - and this is a bit misleading. You mean  Version.txt and not the template. Question was just about to know that I understood it right.

**Comment by Jimrnelson** [comment]
None of my folders have a file named Vsrsion.txt.  They all have a file named VersionTemplate.txt.

The documentation says:

VersionTemplate.txt: contains the template for the Thor CFU version file. Although it has a TXT extension, it actually contains VFP code. This will be used to create the version file for the remote ThorUpdater{AppID}Version.txt file

**Comment by lscheffler** [comment]
@Jimrnelson Just alter the *Source/Apps/VFPXDeployment/VersionTemplate.txt* in VFPXDeployment and push. It still needs to alter this files if used in BuildProcess, but for projects to put under VFPXDeployment, it should be there.

You can also place the code snippet here and I will put it into the file, I will not copy from the picture. And I need https://github.com/VFPX/Thor/pull/149 to test the stuff.

**Comment by Jimrnelson** [comment]
I will certainly get to this when my time permits.

**Pull request merged**
