### PR TITLE
Version 1.46.01

### PR DESCRIPTION
**Pull request by lscheffler**
Unzip with Powershell
Added API_Run

### CODE REVIEW

**Comment by DougHennig** [comment]
@lscheffler Have you had a chance to test this thoroughly? As Jim said, if there is even a minor bug, it pretty much kills Thor CFU for everyone who installs it and there is no way for them to fix it without completing resinstalling Thor, and there is no way for us to tell them that. So, I am nervous about merging this pull request.

**Comment by lscheffler** [comment]
@DougHennig @Jimrnelson    

I really understand your concern. I know what happens if it stucks, I run into it. If have tested (and been testing). But you can give it a try yourself.
All the change is in
- [Installed Files/Thor/Tools/Procs/Thor_Proc_ExtractFilesFromZip.PRG](https://github.com/lscheffler/Thor/blob/master/Installed%20Files/Thor/Tools/Procs/Thor_Proc_ExtractFilesFromZip.PRG)
- [Installed Files/Thor/Tools/Procs/Thor_Proc_RunExtApp.prg](https://github.com/lscheffler/Thor/blob/master/Installed%20Files/Thor/Tools/Procs/Thor_Proc_RunExtApp.prg)

---
For you it should change nothing, since it defaults to Shell. Only if the Shell fails (as with me), it tries PowerShell - with the Run_API, and only if this fails (some may block PowerShell, or run an ancient system without) it uses VFPCompression.dll. The part running Shell is untouched.

And the Unzip of VFPCompression is tested for it's return value.

---
One way to test would to be a download a fresh Thor from [my fork](https://github.com/lscheffler/Thor/archive/refs/heads/master.zip) and check how it works. (Assuming there is no update to Thor since 2023/08/13 07:45 UTC, that would overwrite the unzip prg)    
The other way would be to duplicate your whole Thor, place both files inside your _Proc_ directory and run CFU.

**Comment by lscheffler** [comment]
@DougHennig @Jimrnelson 

Sry I forgot to mention, but if you push a new version, just let me know (I hope I get notified anyway), I simply will do the merge and merge request a new version of this.

**Comment by Jimrnelson** [comment]
> One way to test would to be a download a fresh Thor from [my fork](https://github.com/lscheffler/Thor/archive/refs/heads/master.zip) and check how it works. (Assuming there is no update to Thor since 2023/08/13 07:45 UTC, that would overwrite the unzip prg)
The other way would be to duplicate your whole Thor, place both files inside your Proc directory and run CFU.

The easiest way to test this would be to put those two files in your "My Tools" folder.  They can be erased later.

**Comment by Jimrnelson** [comment]
> But you agree that this is not the same. Anyway, if you trust this way to test, please do. :)

No, you are wrong.

I could not disagree with you more strongly.

A critical design in Thor is the use of the "My Tools" folder.  I have used it hundreds (maybe thousands) of times over the years in my development of Thor to test new code.  All of the changes over time in Thor, particularly CFU, have been tested by using the "My Tools" folder.

I simply cannot believe you would question whether I know how to test in an application that I created and implemented.

**Comment by DougHennig** [comment]
The pull request contains a lot more changes than just the two PRGs you mentioned. Can you revert all the changes except those (for example, we don't need an updated Thor.app)?

**Comment by Jimrnelson** [comment]
> * The merge follow the rules in [CONTRIBUTING.md](https://github.com/VFPX/Thor/blob/master/.github/CONTRIBUTING.md)

Yes, my bad.  I did not anticipate the issue of issuing a pull request that would be immediately merged.  I will correct this in due time.

**Comment by Jimrnelson** [comment]
> * The changes to the files are because the idea to store binary sources to a repo and compile the app before pushing. The binaries are changing due to the way VFP compiles them, so they get committed every time. There is no change. (Or why I hate binary sources in repositories. Nothing then bloat one can not work with)

I agree on this issue for my normal work, but not here.  There is too much room for error if every time I synced from master I had to re-apply text to binary for all affected files.  I would find this especially bothersome as I work on so many repos.

It sure does clutter the repo but I do not see a good way to avoid it.

**Comment by Jimrnelson** [comment]
> If we need to collaborate on code-only base, we need a different approach then merging to master.

I think it would have all worked well if you had only committed the two files you changed, which we could have gotten easily for testing.  (I know you followed the directions, but, in retrospect ...)

The later steps of changing version numbers, etc, would then wait until everything is ready to be released as the real update to Thor.

I will be incorporating this into the changes in  [CONTRIBUTING.md](https://github.com/VFPX/Thor/blob/master/.github/CONTRIBUTING.md)

**Comment by Jimrnelson** [comment]
> I do not like to test what oddities "My Tools" will provide. 

That's really too bad, because it's a really important part of the design of Thor.  Not understanding and using it really limits you.

And, you would not be testing it, because it's been in use for a dozen years.  It's not new (except to you).

The concept is simple:  If a Proc is found in the "My Tools" folder, Thor uses it rather than the one found in the "Procs" folder.

**Comment by lscheffler** [comment]
> 

FoxBin2Prg with Bin2Text I use to solve exactly this. I use it daily for ages, and no binaries in the repo. Much smaller repos, mergable, blame able. It's like a charm.   
I understand that there is a bit of learning and a very odd feeling about this. And for stuff like VFPX it's an extra step for co-workers. But if there is something I hate more then the EXECSCRIPT hell, it's those not maintainable repos.

**Comment by Jimrnelson** [comment]
>  have no nil zero fun in debugging this Excescript hell, and I do not need an extra twist to it.

Yup, debugging with Execscript makes for some fun, but, again, it was a very conscious design decision that produces some highly desirable results.

**Comment by Jimrnelson** [comment]
> And somehow I think a tool as important as the unzipper must be final tested where it belongs, not in a test environment.

It's not a test environment.  It's the same environment, except that Thor calls the same procedure but from the "My Tools" folder.

**Comment by lscheffler** [comment]
> > If we need to collaborate on code-only base, we need a different approach then merging to master.
> 
> I think it would have all worked well if you had only committed the two files you changed, which we could have gotten easily for testing. (I know you followed the directions, but, in retrospect ...)
> 
> The later steps of changing version numbers, etc, would then wait until everything is ready to be released as the real update to Thor.
> 
> I will be incorporating this into the changes in [CONTRIBUTING.md](https://github.com/VFPX/Thor/blob/master/.github/CONTRIBUTING.md)

Sure. Don't get me wrong, the approach is wrong on all the VFPX stuff. Freaks me out every time, and because of that I'm picky what I test.   
You know how to do set up the merge with branches, or do you need help there?

**Comment by lscheffler** [comment]
@DougHennig The way expected would be as follows:
1. You create a new branch [xyz] here for merging
2. I put the pull request to this branch
3. on your local comp
   - make sure your local folder is fully commited
   - git pull -all
   - git switch [xyz] (or try to learn git worktree, for this, that's what I prefer)
   - now you have my state at your comp
   - test it if it runs fine, switch to master, merge [xyz] into it

**Comment by lscheffler** [comment]
> And, you would not be testing it, because it's been in use for a dozen years. It's not new (except to you).

Let's say, if I go to main pages readme, follow the doc link (..complete online documentation), there is nothing I can identify as help to internal work, so it's error and retry.

And again, I first learned the use of "My Updates" - and that it is useless to replace a file in "Updates". Do you really think I will retry on a different combination of directories? So the assumption is _extra tools_, but this is not the problem I have.

**Comment by lscheffler** [comment]
> Yup, debugging with Execscript makes for some fun, but, again, it was a very conscious design decision that produces some highly desirable results.

As far as I remember, this use of EXCECSCRIPT was actively discouraged the time EXCECSCRIPT was introduced.

**Comment by Jimrnelson** [comment]
> As far as I remember, this use of EXCECSCRIPT was actively discouraged the time EXCECSCRIPT was introduced.

I don't care.  It is, in fact, an integral part of the entire design of Thor, achieving many goals actually.  Thor would not be the same without it.

As undesirable it may be to you, it's there and it's not going to change, so just accept it and move on.

**Comment by lscheffler** [comment]
fine

**Comment by Jimrnelson** [comment]
@lscheffler 

> FoxBin2Prg with Bin2Text I use to solve exactly this. I use it daily for ages, and no binaries in the repo. Much smaller repos, mergable, blame able. It's like a charm.
> I understand that there is a bit of learning and a very odd feeling about this. And for stuff like VFPX it's an extra step for co-workers. But if there is something I hate more then the EXECSCRIPT hell, it's those not maintainable repos.

It's not that there's an "odd feeling", it's that one must be very careful to use Bin2Txt in both directions at the right time.

This requires some rigor on the user's part.

And the problem is that some of these projects might be accessed quite infrequently or by users who are not completely aware of the need to use Bin2Txt.  Missing the step in either direction, or possibly using the wrong direction, can really mess things up.

Note that using VFPXDeployment to automatically re-create binaries works just fine.  However, for commits along the way, we do not have an automatic mechanism, nor is there one when we sync or local repos with master.

Beyond that, we do not have any good way to communicate to anybody cloning or working with VFPX repos about the need for Bin2Txt.

**Comment by lscheffler** [comment]
I guess you mix up [Bin2Text](https://github.com/lscheffler/bin2text) with [FoxBin2Prg](https://github.com/fdbozzo/foxbin2prg). The first as a tool to automate and speed up the second, and allow to commit and minor git access.
I consider the following as if you say *FoxBin2Prg*

Note, this answer is academic. This is not suggesting to change the repos.   
ANYWAY; IT'S A UNBEARABLE PAIN. Look at the whole matter here. It's all about this. It bloats the repos (since the binary is not stored as diff), the downloads, the uploads. No merge, endless lists of "changed" files that are not changed, don't get me started. For those public projects I think one should use all text source (IOW prg) only. They are a different kind of pain, but at least one could use the better part of modern tools instead of working VSS like.

> It's not that there's an "odd feeling", it's that one must be very careful to use Bin2Txt in both directions at the right time.
> 
> This requires some rigor on the user's part.

Not more then reading and following CONTRIBUTING.md needs. (Don't get me started. What is not about this merge.)

> And the problem is that some of these projects might be accessed quite infrequently or by users who are not completely aware of the need to use Bin2Txt. Missing the step in either direction, or possibly using the wrong direction, can really mess things up.

Not really. It only requires accessible FoxBin2Prg.exe and git to recreate on checkout / switch / name it. git can start this on the related commands, this is called a hook. One can ship with the repo for all I knew. I only consider it overkill, so I've never done the work. (If I switch between branches / gather stuff I normally do not need to recreate every time. I'm to old for the amount of coffee it needs waiting. I just need the *.??2 files, since I can diff there, pick what I need and recreate after I finished the git side.)
I use [Bin2Text](https://github.com/lscheffler/bin2text) to do Bin2Prg only for changed sources and commit in one step, there is nothing one can do the wrong way. I still think about auto - atomic commits on file change via eventbinding - and later squeeze them.

Also, as long as nobody can _push --force_ to master, the code is save.
 
> Note that using VFPXDeployment to automatically re-create binaries works just fine. 

It's a pain since it blindly runs for all files. And recreates files for nothing, increasing the bloat. Why ever, there is no change in the files but they are listed as completely changed for Thor. Wait. Hell is open, I create a new issue.     

>However, for commits along the way, we do not have an automatic mechanism, nor is there one when we sync or local repos with master.

If you find a moment, check Bin2Text. It's just a menu hit to create the text files for IDE / Active Project and create an automatic commit. Since it trace changes, it runs FoxBin2Prg only for files changed. If you include the binaries to the repo, they will be commited in the same instant.   
If you like to include commit into VFPXDeployment, that's the easy part.


> Beyond that, we do not have any good way to communicate to anybody cloning or working with VFPX repos about the need for Bin2Txt.

As I wrote above, I agree we will not change. It's just frustrating. Thank you for your patience.

**Comment by Jimrnelson** [comment]
> Let's say, if I go to main pages readme, follow the doc link (..complete online documentation), there is nothing I can identify as help to internal work

I am SHOCKED, absolutely SHOCKED, to find that documentation for an application might be incomplete or inaccurate.

> so it's error and retry.

You don't have to work in a vacuum.  This forum is here for you to ask questions and get answers.

**Comment by lscheffler** [comment]
> > Let's say, if I go to main pages readme, follow the doc link (..complete online documentation), there is nothing I can identify as help to internal work
> 
> I am SHOCKED, absolutely SHOCKED, to find that documentation for an application might be incomplete or inaccurate.
> 
> > so it's error and retry.
> 
> You don't have to work in a vacuum. This forum is here for you to ask questions and get answers.

You found the ironic part. I know there is more on the docs folder but normally the problem I work on is NOT Thor. So error and try is faster then searching translating and understanding the needle in the docs. I have other problems to solve.   
You know, it's 22:35, on a regular day I try to quit work when you start, so it's asking here slooow.

**Comment by DougHennig** [comment]
@lscheffler Like Jim, I normally don't include binary files in repositories. However, because many VFP developers are still not familiar with version control and the need for text equivalents of binary files, binary files are included in the VFPX repositories to eliminate the question "where is the source code" that we will certainly get when someone downloads a VFPX project.

**Comment by rschummer** [comment]
While I understand the desire to not bloat the repository with binary source code files, and agree with @DougHennig that it avoids the questions down the road as to "where is the source code", some of us have experienced source code not returning to the original state when it goes through the text to binary process. I once found reports that were getting rounded x,y with fewer decimal. This positioning of the objects gave me pixel alignment issues and a deep distrust in the process. It was quickly fixed when I reported the bug, but to this day I prefer the insurance of having the original source code.

**Comment by Jimrnelson** [comment]
All of our paid work (here at KONG)) is done using GitHub and text files only.

We have a single process that does binary to text before commits and text to binary after.

We have never been aware of any issues with lost or even partially damaged files.

Oh, and because we had many years before GitHub, we also have full nightly backups of all programs, available on line, for the last year.

**Comment by rschummer** [comment]
I understand how you can trust the process when you have not been burned by it. I have been using source code control going back to Visual Source Safe days and have lots of experience where the text files could not be trusted. Most of the time I have been burned by this is when someone forgets to do the binary to text before commits. Once things get out of synch things get hosed. Space is inexpensive. Of course, backups are an insurance policy along with binaries in the repositories for me. Text files are perfect for historical comparisons, and I have used them for this for decades.

**Comment by Jimrnelson** [comment]
I did not mean to imply I simply trust the process.  We just haven't been burned yet.  That's why we still have overnight backups going back a long time.

As for out of sync -- we have a single hot key that initiates the entire process, as mentioned, and anybody caught not using it is taken out behind the barn and whupped.

**Comment by lscheffler** [comment]
@rschummer 
1. git is about  how to work  together. work on different branches, go back in time
2. this should be as easy as possible, and for that text based is the only way
3. git is no backup
4. I mirror my projects each hour or so, some steps stored, and backup those mirror
5. There are still some bugs, and will only find them if we are using FoxBin2Prg. We even found bugs in VFP by having bugs in FoxBin2Prg / using git. See https://github.com/VFPX/HelpFile/issues/31   
6. As like backup needs to test restore before the crash, one most test FoxBin2Prg before deleting binaries. :D 

I had some issues with it, but this is what the backup is for, or even the stuff on a co-workers computer. 
(And one can fix FoxBin2Prg and the *.??2 files, so there is rarely a real lost of data)

And if I would not trust a processes developing, I could hardly sell a program. This risk is built in the whole idea of software. 

The process of looking up changes is soooo much better without the binaries, it's worth the risk. This whole discussion is such a perfect example of it. The change is
- 2 source files
- 2 documentation files
- 2 Thor files

One couldn't even find them in the list of useless commited binaries. Aside the problem with the CRLF.

**Pull request closed without merging**
